import type { HyperParams, ModelId, TaskType } from '../types'

interface CodeGenArgs {
  datasetName: string
  featureColumns: string[]
  targetColumn?: string
  taskType: TaskType
  modelId: ModelId
  hyperParams: HyperParams
  testSize: number
  seed: number
  droppedMissingRows?: boolean
  filledMissingValues?: boolean
  kFolds?: number
}

const SUPERVISED_IMPORTS: Record<ModelId, string> = {
  linear_regression: 'from sklearn.linear_model import LinearRegression',
  ridge_regression: 'from sklearn.linear_model import Ridge',
  logistic_regression: 'from sklearn.linear_model import LogisticRegression',
  naive_bayes: 'from sklearn.naive_bayes import GaussianNB',
  decision_tree: 'from sklearn.tree import DecisionTreeRegressor, DecisionTreeClassifier',
  random_forest: 'from sklearn.ensemble import RandomForestRegressor, RandomForestClassifier',
  knn: 'from sklearn.neighbors import KNeighborsRegressor, KNeighborsClassifier',
  gradient_boosting: 'from sklearn.ensemble import GradientBoostingRegressor, GradientBoostingClassifier',
  svm: 'from sklearn.svm import SVR, SVC',
  xgboost: 'from xgboost import XGBRegressor, XGBClassifier',
  kmeans: 'from sklearn.cluster import KMeans',
  dbscan: 'from sklearn.cluster import DBSCAN',
}

function modelConstructor(modelId: ModelId, taskType: TaskType, hp: HyperParams, seed: number): string {
  const isReg = taskType === 'regression'
  switch (modelId) {
    case 'linear_regression':
      return 'LinearRegression()'
    case 'ridge_regression':
      return `Ridge(alpha=${hp.alpha ?? 1.0}, random_state=${seed})`
    case 'logistic_regression':
      return `LogisticRegression(max_iter=1000, random_state=${seed})`
    case 'naive_bayes':
      return 'GaussianNB()'
    case 'decision_tree':
      return `${isReg ? 'DecisionTreeRegressor' : 'DecisionTreeClassifier'}(max_depth=${hp.maxDepth ?? 6}, min_samples_leaf=${hp.minSamplesLeaf ?? 3}, random_state=${seed})`
    case 'random_forest':
      return `${isReg ? 'RandomForestRegressor' : 'RandomForestClassifier'}(n_estimators=${hp.nEstimators ?? 100}, max_depth=${hp.maxDepth ?? 8}, random_state=${seed})`
    case 'knn':
      return `${isReg ? 'KNeighborsRegressor' : 'KNeighborsClassifier'}(n_neighbors=${hp.k ?? 5})`
    case 'gradient_boosting':
      return `${isReg ? 'GradientBoostingRegressor' : 'GradientBoostingClassifier'}(n_estimators=${hp.nEstimators ?? 80}, learning_rate=${hp.learningRate ?? 0.1}, max_depth=${hp.maxDepth ?? 3}, random_state=${seed})`
    case 'svm':
      return `${isReg ? 'SVR()' : `SVC(probability=True, random_state=${seed})`}`
    case 'xgboost':
      return `${isReg ? 'XGBRegressor' : 'XGBClassifier'}(n_estimators=${hp.nEstimators ?? 100}, learning_rate=${hp.learningRate ?? 0.1}, random_state=${seed})`
    case 'kmeans':
      return `KMeans(n_clusters=${hp.nClusters ?? 3}, random_state=${seed}, n_init="auto")`
    case 'dbscan':
      return `DBSCAN(eps=${hp.eps ?? 0.5}, min_samples=${hp.minPoints ?? 5})`
    default:
      return 'None'
  }
}

export function generatePythonCode(args: CodeGenArgs): string {
  const {
    datasetName,
    featureColumns,
    targetColumn,
    taskType,
    modelId,
    hyperParams,
    testSize,
    seed,
    droppedMissingRows,
    filledMissingValues,
  } = args

  const lines: string[] = []
  lines.push('# Generated by DataForge ML — reproducible research code')
  lines.push('# This mirrors the workflow you built in the app using pandas and scikit-learn.')
  lines.push('')
  lines.push('import pandas as pd')
  lines.push('from sklearn.model_selection import train_test_split')
  if (taskType !== 'clustering') {
    lines.push('from sklearn.preprocessing import StandardScaler')
  } else {
    lines.push('from sklearn.preprocessing import StandardScaler')
    lines.push('from sklearn.decomposition import PCA')
  }
  lines.push(SUPERVISED_IMPORTS[modelId])
  lines.push('')
  lines.push(`RANDOM_SEED = ${seed}`)
  lines.push('')
  lines.push(`# 1. Load your data`)
  lines.push(`df = pd.read_csv("${datasetName}")`)
  lines.push('')

  if (droppedMissingRows) {
    lines.push('# 2. Remove rows with any missing values')
    lines.push('df = df.dropna()')
    lines.push('')
  } else if (filledMissingValues) {
    lines.push('# 2. Fill missing values (numeric columns -> median, categorical columns -> most common value)')
    lines.push('for col in df.select_dtypes(include="number").columns:')
    lines.push('    df[col] = df[col].fillna(df[col].median())')
    lines.push('for col in df.select_dtypes(exclude="number").columns:')
    lines.push('    mode = df[col].mode()')
    lines.push('    if not mode.empty:')
    lines.push('        df[col] = df[col].fillna(mode.iloc[0])')
    lines.push('')
  }

  const featureList = featureColumns.map((f) => `"${f}"`).join(', ')

  if (taskType === 'clustering') {
    lines.push('# 3. Select the columns to analyze and one-hot encode any categorical columns')
    lines.push(`feature_columns = [${featureList}]`)
    lines.push('X = pd.get_dummies(df[feature_columns])')
    lines.push('')
    lines.push('# 4. Scale features so no single measurement dominates the analysis')
    lines.push('X_scaled = StandardScaler().fit_transform(X)')
    lines.push('')
    lines.push('# 5. Find patterns / groups')
    lines.push(`model = ${modelConstructor(modelId, taskType, hyperParams, seed)}`)
    lines.push(modelId === 'kmeans' ? 'labels = model.fit_predict(X_scaled)' : 'labels = model.fit_predict(X_scaled)')
    lines.push('df["cluster"] = labels')
    lines.push('')
    lines.push('# 6. (Optional) 2D visualization with PCA')
    lines.push('coords = PCA(n_components=2, random_state=RANDOM_SEED).fit_transform(X_scaled)')
    lines.push('print(df["cluster"].value_counts())')
    return lines.join('\n')
  }

  lines.push('# 3. Select your features and target')
  lines.push(`feature_columns = [${featureList}]`)
  lines.push(`target_column = "${targetColumn}"`)
  lines.push('')
  lines.push('X = pd.get_dummies(df[feature_columns])')
  lines.push('y = df[target_column]')
  lines.push('')
  lines.push('# 4. Split into training and testing sets')
  lines.push(
    `X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=${testSize}, random_state=RANDOM_SEED)`
  )
  lines.push('')

  const needsScaling = ['linear_regression', 'ridge_regression', 'logistic_regression', 'knn', 'svm'].includes(modelId)
  if (needsScaling) {
    lines.push('# 5. Scale features (this model is sensitive to differences in scale)')
    lines.push('scaler = StandardScaler()')
    lines.push('X_train = scaler.fit_transform(X_train)')
    lines.push('X_test = scaler.transform(X_test)')
    lines.push('')
  }

  lines.push('# 6. Train the model')
  lines.push(`model = ${modelConstructor(modelId, taskType, hyperParams, seed)}`)
  lines.push('model.fit(X_train, y_train)')
  lines.push('')
  lines.push('# 7. Make predictions on held-out test data')
  lines.push('predictions = model.predict(X_test)')
  lines.push('')

  if (taskType === 'regression') {
    lines.push('# 8. Evaluate')
    lines.push('from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score')
    lines.push('mae = mean_absolute_error(y_test, predictions)')
    lines.push('rmse = mean_squared_error(y_test, predictions) ** 0.5')
    lines.push('r2 = r2_score(y_test, predictions)')
    lines.push('print(f"MAE: {mae:.4f}  RMSE: {rmse:.4f}  R2: {r2:.4f}")')
  } else {
    lines.push('# 8. Evaluate')
    lines.push('from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix')
    lines.push('accuracy = accuracy_score(y_test, predictions)')
    lines.push('precision = precision_score(y_test, predictions, average="macro", zero_division=0)')
    lines.push('recall = recall_score(y_test, predictions, average="macro", zero_division=0)')
    lines.push('f1 = f1_score(y_test, predictions, average="macro", zero_division=0)')
    lines.push('print(f"Accuracy: {accuracy:.4f}  Precision: {precision:.4f}  Recall: {recall:.4f}  F1: {f1:.4f}")')
    lines.push('print(confusion_matrix(y_test, predictions))')
  }

  if (args.kFolds && args.kFolds >= 2) {
    lines.push('')
    lines.push(`# 9. ${args.kFolds}-fold cross-validation (fits ${args.kFolds} fresh models on rotating folds)`)
    lines.push('from sklearn.model_selection import cross_val_score')
    lines.push(
      `cv_scores = cross_val_score(${modelConstructor(modelId, taskType, hyperParams, seed)}, X, y, cv=${args.kFolds}, scoring=${
        taskType === 'regression' ? "'r2'" : "'accuracy'"
      })`
    )
    lines.push('print(f"CV scores: {cv_scores}")')
    lines.push('print(f"Mean: {cv_scores.mean():.4f}  Std: {cv_scores.std():.4f}")')
  }

  return lines.join('\n')
}
